-- ============================================================
-- SmartEye — Complete Supabase SQL Schema (Custom Auth)
-- ============================================================
-- Blind IDs are AUTO-GENERATED by a database trigger.
-- Safe to re-run. Run in Supabase SQL Editor.
-- ============================================================
-- ⚠️  If you ran the old schema, drop old tables first:
--     DROP TABLE IF EXISTS public.activity_logs CASCADE;
--     DROP TABLE IF EXISTS public.blind_unique_ids CASCADE;
--     DROP TABLE IF EXISTS public.caretaker_users CASCADE;
--     DROP TABLE IF EXISTS public.blind_users CASCADE;
--     DROP TABLE IF EXISTS public.profiles CASCADE;
--     DROP TABLE IF EXISTS public.user_credentials CASCADE;
-- ============================================================


-- ┌──────────────────────────────────────────────────────────┐
-- │  1. USER_CREDENTIALS  (custom email + password auth)     │
-- └──────────────────────────────────────────────────────────┘
CREATE TABLE IF NOT EXISTS public.user_credentials (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email         TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role          TEXT NOT NULL CHECK (role IN ('blind', 'caretaker')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.user_credentials DISABLE ROW LEVEL SECURITY;


-- ┌──────────────────────────────────────────────────────────┐
-- │  2. BLIND_USERS  (full blind-user profile)               │
-- │  blind_unique_id is AUTO-GENERATED by a trigger below.   │
-- └──────────────────────────────────────────────────────────┘
CREATE TABLE IF NOT EXISTS public.blind_users (
  id               UUID PRIMARY KEY REFERENCES public.user_credentials(id) ON DELETE CASCADE,
  blind_unique_id  TEXT UNIQUE,                    -- auto-generated by trigger

  -- Personal details
  blind_name       TEXT,
  full_name        TEXT NOT NULL,
  profile_photo_url TEXT,

  -- Medical details
  blood_group      TEXT,
  age              INTEGER CHECK (age > 0 AND age < 200),
  date_of_birth    DATE,
  disease_condition TEXT,

  -- Address information
  address_line_1   TEXT,
  address_line_2   TEXT,

  -- Caretaker details
  caretaker_name   TEXT,
  caretaker_email  TEXT NOT NULL,
  caretaker_phone  TEXT,

  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.blind_users DISABLE ROW LEVEL SECURITY;


-- ┌──────────────────────────────────────────────────────────┐
-- │  AUTO-GENERATE blind_unique_id ON INSERT                 │
-- │  Format: SE-XXXXXX  (6 random alphanumeric chars)        │
-- │  Guaranteed unique by retry loop.                        │
-- └──────────────────────────────────────────────────────────┘
CREATE OR REPLACE FUNCTION public.generate_blind_unique_id()
RETURNS TRIGGER AS $$
DECLARE
  chars       TEXT := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  new_id      TEXT;
  id_exists   BOOLEAN;
BEGIN
  -- Only generate if not already set
  IF NEW.blind_unique_id IS NULL OR NEW.blind_unique_id = '' THEN
    LOOP
      -- Build SE- + 6 random characters
      new_id := 'SE-';
      FOR i IN 1..6 LOOP
        new_id := new_id || substr(chars, floor(random() * length(chars) + 1)::int, 1);
      END LOOP;

      -- Check uniqueness
      SELECT EXISTS(
        SELECT 1 FROM public.blind_users WHERE blind_unique_id = new_id
      ) INTO id_exists;

      EXIT WHEN NOT id_exists;  -- unique → use it
    END LOOP;

    NEW.blind_unique_id := new_id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_generate_blind_id ON public.blind_users;
CREATE TRIGGER trigger_generate_blind_id
  BEFORE INSERT ON public.blind_users
  FOR EACH ROW EXECUTE FUNCTION public.generate_blind_unique_id();


-- ┌──────────────────────────────────────────────────────────┐
-- │  3. CARETAKER_USERS                                      │
-- └──────────────────────────────────────────────────────────┘
CREATE TABLE IF NOT EXISTS public.caretaker_users (
  id                   UUID PRIMARY KEY REFERENCES public.user_credentials(id) ON DELETE CASCADE,
  email                TEXT NOT NULL,
  linked_blind_user_id UUID REFERENCES public.blind_users(id) ON DELETE SET NULL,
  blind_unique_id      TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.caretaker_users DISABLE ROW LEVEL SECURITY;


-- ┌──────────────────────────────────────────────────────────┐
-- │  4. BLIND_UNIQUE_IDS  (ID verification & claim table)    │
-- └──────────────────────────────────────────────────────────┘
CREATE TABLE IF NOT EXISTS public.blind_unique_ids (
  id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  blind_user_id   UUID NOT NULL REFERENCES public.blind_users(id) ON DELETE CASCADE,
  unique_id       TEXT UNIQUE NOT NULL,
  caretaker_email TEXT NOT NULL,
  is_claimed      BOOLEAN NOT NULL DEFAULT false,
  claimed_by      UUID REFERENCES public.user_credentials(id),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.blind_unique_ids DISABLE ROW LEVEL SECURITY;


-- ┌──────────────────────────────────────────────────────────┐
-- │  5. ACTIVITY_LOGS  (audit trail)                         │
-- └──────────────────────────────────────────────────────────┘
CREATE TABLE IF NOT EXISTS public.activity_logs (
  id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id    UUID NOT NULL REFERENCES public.user_credentials(id) ON DELETE CASCADE,
  action     TEXT NOT NULL,
  details    TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.activity_logs DISABLE ROW LEVEL SECURITY;


-- ┌──────────────────────────────────────────────────────────┐
-- │  6. HELPER: auto-update `updated_at` timestamp           │
-- └──────────────────────────────────────────────────────────┘
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_blind_users_updated_at ON public.blind_users;
CREATE TRIGGER set_blind_users_updated_at
  BEFORE UPDATE ON public.blind_users
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_caretaker_users_updated_at ON public.caretaker_users;
CREATE TRIGGER set_caretaker_users_updated_at
  BEFORE UPDATE ON public.caretaker_users
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();


-- ┌──────────────────────────────────────────────────────────┐
-- │  7. USEFUL INDEXES                                       │
-- └──────────────────────────────────────────────────────────┘
CREATE INDEX IF NOT EXISTS idx_credentials_email    ON public.user_credentials(email);
CREATE INDEX IF NOT EXISTS idx_credentials_role     ON public.user_credentials(role);
CREATE INDEX IF NOT EXISTS idx_blind_users_unique   ON public.blind_users(blind_unique_id);
CREATE INDEX IF NOT EXISTS idx_blind_ids_unique     ON public.blind_unique_ids(unique_id);
CREATE INDEX IF NOT EXISTS idx_activity_user        ON public.activity_logs(user_id);


-- ============================================================
-- HOW IT WORKS
-- ============================================================
-- 1. Blind user signs up → row inserted into blind_users
-- 2. The trigger auto-generates a unique SE-XXXXXX blind ID
-- 3. Your Flutter app reads the generated ID back from the DB
-- 4. The ID is emailed to the caretaker (via Edge Function)
-- 5. Caretaker enters this ID during their sign-up to link
--    their account to the blind user
-- ============================================================
