import 'dart:convert';
import 'package:crypto/crypto.dart';
import 'package:flutter/foundation.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:uuid/uuid.dart';

/// Centralized authentication and database service for SmartEye.
/// Uses a custom `user_credentials` table instead of Supabase Auth.
class AuthService {
  final SupabaseClient _client = Supabase.instance.client;
  static const _uuid = Uuid();

  /// Currently logged-in user info (kept in memory)
  String? currentUserId;
  String? currentUserEmail;
  String? currentUserRole;

  // ─────────────────────────────────────────────────────────────
  // PASSWORD HASHING (SHA-256)
  // ─────────────────────────────────────────────────────────────
  String _hashPassword(String password) {
    final bytes = utf8.encode(password);
    return sha256.convert(bytes).toString();
  }

  // ─────────────────────────────────────────────────────────────
  // BLIND USER SIGN UP
  // ─────────────────────────────────────────────────────────────
  Future<String> signUpBlindUser({
    required String email,
    required String password,
    required String fullName,
    required int age,
    required String bloodGroup,
    required String caretakerEmail,
    String? blindName,
    String? dateOfBirth,
    String? diseaseCondition,
    String? addressLine1,
    String? addressLine2,
    String? caretakerName,
    String? caretakerPhone,
  }) async {
    // 1. Check if email already exists
    final existing = await _client
        .from('user_credentials')
        .select('id')
        .eq('email', email)
        .maybeSingle();

    if (existing != null) {
      throw Exception('An account with this email already exists.');
    }

    // 2. Create user credentials
    final userId = _uuid.v4();
    final passwordHash = _hashPassword(password);

    await _client.from('user_credentials').insert({
      'id': userId,
      'email': email,
      'password_hash': passwordHash,
      'role': 'blind',
    });

    // 3. Insert into blind_users (blind_unique_id is AUTO-GENERATED by DB trigger)
    final blindUserData = <String, dynamic>{
      'id': userId,
      // blind_unique_id is NOT set here — the DB trigger generates it
      'blind_name': blindName,
      'full_name': fullName,
      'blood_group': bloodGroup,
      'age': age,
      'date_of_birth': dateOfBirth,
      'disease_condition': diseaseCondition,
      'address_line_1': addressLine1,
      'address_line_2': addressLine2,
      'caretaker_name': caretakerName,
      'caretaker_email': caretakerEmail,
      'caretaker_phone': caretakerPhone,
    };
    // Remove null/empty values so Supabase uses column defaults
    blindUserData.removeWhere((_, v) => v == null || (v is String && v.isEmpty));

    // Insert and read back the auto-generated blind_unique_id
    final insertedRow = await _client
        .from('blind_users')
        .insert(blindUserData)
        .select('blind_unique_id')
        .single();

    final blindId = insertedRow['blind_unique_id'] as String;

    // 4. Insert into blind_unique_ids table (for caretaker verification)
    await _client.from('blind_unique_ids').insert({
      'blind_user_id': userId,
      'unique_id': blindId,
      'caretaker_email': caretakerEmail,
      'is_claimed': false,
    });

    // 6. Send the Blind ID to the caretaker's email via Edge Function
    try {
      await _client.functions.invoke(
        'send-blind-id-email',
        body: {
          'caretaker_email': caretakerEmail,
          'blind_id': blindId,
          'blind_user_name': fullName,
        },
      );
    } catch (e) {
      debugPrint('[AuthService] Edge Function not available: $e');
    }

    // 7. Set current session in memory
    currentUserId = userId;
    currentUserEmail = email;
    currentUserRole = 'blind';

    // 8. Log activity
    await _logActivity(
      userId: userId,
      action: 'blind_signup',
      details: 'Blind ID generated and emailed to $caretakerEmail',
    );

    return blindId;
  }

  // ─────────────────────────────────────────────────────────────
  // CARETAKER SIGN UP
  // ─────────────────────────────────────────────────────────────
  Future<void> signUpCaretakerUser({
    required String email,
    required String password,
    required String blindUniqueId,
  }) async {
    // 1. Verify Blind ID exists and is unclaimed
    final idCheck = await _client
        .from('blind_unique_ids')
        .select('blind_user_id, is_claimed')
        .eq('unique_id', blindUniqueId)
        .maybeSingle();

    if (idCheck == null) {
      throw Exception(
          'Invalid Blind ID. Please check the ID sent to your caretaker email.');
    }

    if (idCheck['is_claimed'] == true) {
      throw Exception(
          'This Blind ID has already been claimed by another caretaker.');
    }

    final linkedBlindUserId = idCheck['blind_user_id'] as String;

    // 2. Check if email already exists
    final existing = await _client
        .from('user_credentials')
        .select('id')
        .eq('email', email)
        .maybeSingle();

    if (existing != null) {
      throw Exception('An account with this email already exists.');
    }

    // 3. Create user credentials
    final userId = _uuid.v4();
    final passwordHash = _hashPassword(password);

    await _client.from('user_credentials').insert({
      'id': userId,
      'email': email,
      'password_hash': passwordHash,
      'role': 'caretaker',
    });

    // 4. Insert into caretaker_users table
    await _client.from('caretaker_users').insert({
      'id': userId,
      'linked_blind_user_id': linkedBlindUserId,
      'blind_unique_id': blindUniqueId,
      'email': email,
    });

    // 5. Mark Blind ID as claimed
    await _client
        .from('blind_unique_ids')
        .update({'is_claimed': true, 'claimed_by': userId})
        .eq('unique_id', blindUniqueId);

    // 6. Set current session in memory
    currentUserId = userId;
    currentUserEmail = email;
    currentUserRole = 'caretaker';

    // 7. Log activity
    await _logActivity(
      userId: userId,
      action: 'caretaker_signup',
      details: 'Linked to blind user: $linkedBlindUserId',
    );
  }

  // ─────────────────────────────────────────────────────────────
  // SIGN IN (both roles)
  // Compares email + hashed password against user_credentials.
  // ─────────────────────────────────────────────────────────────
  Future<Map<String, dynamic>> signIn({
    required String email,
    required String password,
  }) async {
    final passwordHash = _hashPassword(password);

    final result = await _client
        .from('user_credentials')
        .select('id, email, role, password_hash')
        .eq('email', email)
        .maybeSingle();

    if (result == null) {
      throw Exception('No account found with this email.');
    }

    if (result['password_hash'] != passwordHash) {
      throw Exception('Incorrect password. Please try again.');
    }

    // Set current session in memory
    currentUserId = result['id'] as String;
    currentUserEmail = result['email'] as String;
    currentUserRole = result['role'] as String;

    await _logActivity(
      userId: currentUserId!,
      action: 'sign_in',
      details: 'User signed in successfully',
    );

    return {
      'id': currentUserId,
      'email': currentUserEmail,
      'role': currentUserRole,
    };
  }

  // ─────────────────────────────────────────────────────────────
  // GET USER ROLE
  // ─────────────────────────────────────────────────────────────
  String? getUserRole() {
    return currentUserRole;
  }

  // ─────────────────────────────────────────────────────────────
  // CHECK IF LOGGED IN
  // ─────────────────────────────────────────────────────────────
  bool get isLoggedIn => currentUserId != null;

  // ─────────────────────────────────────────────────────────────
  // SIGN OUT
  // ─────────────────────────────────────────────────────────────
  Future<void> signOut() async {
    if (currentUserId != null) {
      await _logActivity(
        userId: currentUserId!,
        action: 'sign_out',
        details: 'User signed out',
      );
    }
    currentUserId = null;
    currentUserEmail = null;
    currentUserRole = null;
  }

  // blind_unique_id is now auto-generated by the database trigger.
  // No client-side ID generation needed.

  // ─────────────────────────────────────────────────────────────
  // PRIVATE: Log Activity
  // ─────────────────────────────────────────────────────────────
  Future<void> _logActivity({
    required String userId,
    required String action,
    required String details,
  }) async {
    try {
      await _client.from('activity_logs').insert({
        'user_id': userId,
        'action': action,
        'details': details,
        'created_at': DateTime.now().toIso8601String(),
      });
    } catch (e) {
      debugPrint('[AuthService] _logActivity error: $e');
    }
  }
}

/// Global instance for use across the app
final authService = AuthService();
